name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up CMake
      run: sudo apt-get install cmake ninja-build g++

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Configure project
      run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ./build/example
      run: ./build/ntest_selftest

